#!/usr/bin/env bash
# Install Nginx Server , Configure Index page, add a custome Header
apt-get update -y
apt-get install nginx
echo "Ok!" > /var/www/html/index.html
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/&\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start