#!/usr/bin/env bash
# Install Nginx Server , Configure Index page, add a custome Header

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend younes
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 379988-web-01 54.89.194.187:80 check
    server 379988-web-02 54.157.141.63:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart