#!/usr/bin/env bash
# This Script Print "Best School" work 10 times but if it the 9 it print Hi 

i=0

while [ $i -lt 10 ];
do
	if [ $i == 8 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
