#!/usr/bin/env bash
# Nginx run as nginx user
pkill apache2
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service nginx start
